version: "3"
services:
  bludgeon_database:
    container_name: "bludgeon_database"
    image: bludgeon_db-mysql:latest
    restart: "always"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - bludgeon-database-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bludgeon
      MYSQL_DATABASE: bludgeon
      MYSQL_USER: bludgeon
      MYSQL_PASSWORD: bludgeon
volumes:
  bludgeon-database-mysql:
