//
//go_bludgeon_employees defines a set of types for use with the employees service

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: employees.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmployeeCreateRequest
type EmployeeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employee_partial
	EmployeePartial *EmployeePartial `protobuf:"bytes,1,opt,name=employee_partial,json=employeePartial,proto3" json:"employee_partial,omitempty"`
}

func (x *EmployeeCreateRequest) Reset() {
	*x = EmployeeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCreateRequest) ProtoMessage() {}

func (x *EmployeeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCreateRequest.ProtoReflect.Descriptor instead.
func (*EmployeeCreateRequest) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeCreateRequest) GetEmployeePartial() *EmployeePartial {
	if x != nil {
		return x.EmployeePartial
	}
	return nil
}

// EmployeeCreateResponse
type EmployeeCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employee
	Employee *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *EmployeeCreateResponse) Reset() {
	*x = EmployeeCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCreateResponse) ProtoMessage() {}

func (x *EmployeeCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCreateResponse.ProtoReflect.Descriptor instead.
func (*EmployeeCreateResponse) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeCreateResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// EmployeeReadRequest
type EmployeeReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EmployeeReadRequest) Reset() {
	*x = EmployeeReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeReadRequest) ProtoMessage() {}

func (x *EmployeeReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeReadRequest.ProtoReflect.Descriptor instead.
func (*EmployeeReadRequest) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EmployeeReadResponse
type EmployeeReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employee
	Employee *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *EmployeeReadResponse) Reset() {
	*x = EmployeeReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeReadResponse) ProtoMessage() {}

func (x *EmployeeReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeReadResponse.ProtoReflect.Descriptor instead.
func (*EmployeeReadResponse) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{3}
}

func (x *EmployeeReadResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// EmployeesReadRequest
type EmployeesReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employee_search
	EmployeeSearch *EmployeeSearch `protobuf:"bytes,1,opt,name=employee_search,json=employeeSearch,proto3" json:"employee_search,omitempty"`
}

func (x *EmployeesReadRequest) Reset() {
	*x = EmployeesReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeesReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeesReadRequest) ProtoMessage() {}

func (x *EmployeesReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeesReadRequest.ProtoReflect.Descriptor instead.
func (*EmployeesReadRequest) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{4}
}

func (x *EmployeesReadRequest) GetEmployeeSearch() *EmployeeSearch {
	if x != nil {
		return x.EmployeeSearch
	}
	return nil
}

// EmployeesReadResponse
type EmployeesReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employees
	Employees []*Employee `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
}

func (x *EmployeesReadResponse) Reset() {
	*x = EmployeesReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeesReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeesReadResponse) ProtoMessage() {}

func (x *EmployeesReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeesReadResponse.ProtoReflect.Descriptor instead.
func (*EmployeesReadResponse) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{5}
}

func (x *EmployeesReadResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

// EmployeeUpdateRequest
type EmployeeUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// employee_partial
	EmployeePartial *EmployeePartial `protobuf:"bytes,2,opt,name=employee_partial,json=employeePartial,proto3" json:"employee_partial,omitempty"`
}

func (x *EmployeeUpdateRequest) Reset() {
	*x = EmployeeUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeUpdateRequest) ProtoMessage() {}

func (x *EmployeeUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeUpdateRequest.ProtoReflect.Descriptor instead.
func (*EmployeeUpdateRequest) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeUpdateRequest) GetEmployeePartial() *EmployeePartial {
	if x != nil {
		return x.EmployeePartial
	}
	return nil
}

// EmployeeUpdateResponse
type EmployeeUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// employee
	Employee *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *EmployeeUpdateResponse) Reset() {
	*x = EmployeeUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeUpdateResponse) ProtoMessage() {}

func (x *EmployeeUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeUpdateResponse.ProtoReflect.Descriptor instead.
func (*EmployeeUpdateResponse) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{7}
}

func (x *EmployeeUpdateResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// EmployeeDeleteRequest
type EmployeeDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EmployeeDeleteRequest) Reset() {
	*x = EmployeeDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeDeleteRequest) ProtoMessage() {}

func (x *EmployeeDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeDeleteRequest.ProtoReflect.Descriptor instead.
func (*EmployeeDeleteRequest) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{8}
}

func (x *EmployeeDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EmployeeDeleteResponse
type EmployeeDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmployeeDeleteResponse) Reset() {
	*x = EmployeeDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeDeleteResponse) ProtoMessage() {}

func (x *EmployeeDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeDeleteResponse.ProtoReflect.Descriptor instead.
func (*EmployeeDeleteResponse) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{9}
}

// EmployeePartial
type EmployeePartial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// first_name_oneof
	//
	// Types that are assignable to FirstNameOneof:
	//
	//	*EmployeePartial_FirstName
	FirstNameOneof isEmployeePartial_FirstNameOneof `protobuf_oneof:"first_name_oneof"`
	// last_name_oneof
	//
	// Types that are assignable to LastNameOneof:
	//
	//	*EmployeePartial_LastName
	LastNameOneof isEmployeePartial_LastNameOneof `protobuf_oneof:"last_name_oneof"`
	// email_addressoneof
	//
	// Types that are assignable to EmailAddressOneof:
	//
	//	*EmployeePartial_EmailAddress
	EmailAddressOneof isEmployeePartial_EmailAddressOneof `protobuf_oneof:"email_address_oneof"`
}

func (x *EmployeePartial) Reset() {
	*x = EmployeePartial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeePartial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeePartial) ProtoMessage() {}

func (x *EmployeePartial) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeePartial.ProtoReflect.Descriptor instead.
func (*EmployeePartial) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{10}
}

func (m *EmployeePartial) GetFirstNameOneof() isEmployeePartial_FirstNameOneof {
	if m != nil {
		return m.FirstNameOneof
	}
	return nil
}

func (x *EmployeePartial) GetFirstName() string {
	if x, ok := x.GetFirstNameOneof().(*EmployeePartial_FirstName); ok {
		return x.FirstName
	}
	return ""
}

func (m *EmployeePartial) GetLastNameOneof() isEmployeePartial_LastNameOneof {
	if m != nil {
		return m.LastNameOneof
	}
	return nil
}

func (x *EmployeePartial) GetLastName() string {
	if x, ok := x.GetLastNameOneof().(*EmployeePartial_LastName); ok {
		return x.LastName
	}
	return ""
}

func (m *EmployeePartial) GetEmailAddressOneof() isEmployeePartial_EmailAddressOneof {
	if m != nil {
		return m.EmailAddressOneof
	}
	return nil
}

func (x *EmployeePartial) GetEmailAddress() string {
	if x, ok := x.GetEmailAddressOneof().(*EmployeePartial_EmailAddress); ok {
		return x.EmailAddress
	}
	return ""
}

type isEmployeePartial_FirstNameOneof interface {
	isEmployeePartial_FirstNameOneof()
}

type EmployeePartial_FirstName struct {
	// first_name
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof"`
}

func (*EmployeePartial_FirstName) isEmployeePartial_FirstNameOneof() {}

type isEmployeePartial_LastNameOneof interface {
	isEmployeePartial_LastNameOneof()
}

type EmployeePartial_LastName struct {
	// last_name
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof"`
}

func (*EmployeePartial_LastName) isEmployeePartial_LastNameOneof() {}

type isEmployeePartial_EmailAddressOneof interface {
	isEmployeePartial_EmailAddressOneof()
}

type EmployeePartial_EmailAddress struct {
	// email_address
	EmailAddress string `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3,oneof"`
}

func (*EmployeePartial_EmailAddress) isEmployeePartial_EmailAddressOneof() {}

// Employee
type Employee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// first_name
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// last_name
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// email_address
	EmailAddress string `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// last_udpated
	LastUdpated int64 `protobuf:"varint,5,opt,name=last_udpated,json=lastUdpated,proto3" json:"last_udpated,omitempty"`
	// last_updated_by
	LastUpdatedBy string `protobuf:"bytes,6,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by,omitempty"`
	// version
	Version int32 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Employee) Reset() {
	*x = Employee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{11}
}

func (x *Employee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *Employee) GetLastUdpated() int64 {
	if x != nil {
		return x.LastUdpated
	}
	return 0
}

func (x *Employee) GetLastUpdatedBy() string {
	if x != nil {
		return x.LastUpdatedBy
	}
	return ""
}

func (x *Employee) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// EmployeeSearch
type EmployeeSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ids
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// first_names
	FirstNames []string `protobuf:"bytes,2,rep,name=first_names,json=firstNames,proto3" json:"first_names,omitempty"`
	// first_name_oneof
	//
	// Types that are assignable to FirstNameOneof:
	//
	//	*EmployeeSearch_FirstName
	FirstNameOneof isEmployeeSearch_FirstNameOneof `protobuf_oneof:"first_name_oneof"`
	// last_names
	LastNames []string `protobuf:"bytes,4,rep,name=last_names,json=lastNames,proto3" json:"last_names,omitempty"`
	// last_name_oneof
	//
	// Types that are assignable to LastNameOneof:
	//
	//	*EmployeeSearch_LastName
	LastNameOneof isEmployeeSearch_LastNameOneof `protobuf_oneof:"last_name_oneof"`
	// email_addressoneof
	//
	// Types that are assignable to EmailAddressOneof:
	//
	//	*EmployeeSearch_EmailAddress
	EmailAddressOneof isEmployeeSearch_EmailAddressOneof `protobuf_oneof:"email_address_oneof"`
	// email_addresses
	EmailAddresses []string `protobuf:"bytes,7,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
}

func (x *EmployeeSearch) Reset() {
	*x = EmployeeSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSearch) ProtoMessage() {}

func (x *EmployeeSearch) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSearch.ProtoReflect.Descriptor instead.
func (*EmployeeSearch) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{12}
}

func (x *EmployeeSearch) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *EmployeeSearch) GetFirstNames() []string {
	if x != nil {
		return x.FirstNames
	}
	return nil
}

func (m *EmployeeSearch) GetFirstNameOneof() isEmployeeSearch_FirstNameOneof {
	if m != nil {
		return m.FirstNameOneof
	}
	return nil
}

func (x *EmployeeSearch) GetFirstName() string {
	if x, ok := x.GetFirstNameOneof().(*EmployeeSearch_FirstName); ok {
		return x.FirstName
	}
	return ""
}

func (x *EmployeeSearch) GetLastNames() []string {
	if x != nil {
		return x.LastNames
	}
	return nil
}

func (m *EmployeeSearch) GetLastNameOneof() isEmployeeSearch_LastNameOneof {
	if m != nil {
		return m.LastNameOneof
	}
	return nil
}

func (x *EmployeeSearch) GetLastName() string {
	if x, ok := x.GetLastNameOneof().(*EmployeeSearch_LastName); ok {
		return x.LastName
	}
	return ""
}

func (m *EmployeeSearch) GetEmailAddressOneof() isEmployeeSearch_EmailAddressOneof {
	if m != nil {
		return m.EmailAddressOneof
	}
	return nil
}

func (x *EmployeeSearch) GetEmailAddress() string {
	if x, ok := x.GetEmailAddressOneof().(*EmployeeSearch_EmailAddress); ok {
		return x.EmailAddress
	}
	return ""
}

func (x *EmployeeSearch) GetEmailAddresses() []string {
	if x != nil {
		return x.EmailAddresses
	}
	return nil
}

type isEmployeeSearch_FirstNameOneof interface {
	isEmployeeSearch_FirstNameOneof()
}

type EmployeeSearch_FirstName struct {
	// first_name
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof"`
}

func (*EmployeeSearch_FirstName) isEmployeeSearch_FirstNameOneof() {}

type isEmployeeSearch_LastNameOneof interface {
	isEmployeeSearch_LastNameOneof()
}

type EmployeeSearch_LastName struct {
	// last_name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof"`
}

func (*EmployeeSearch_LastName) isEmployeeSearch_LastNameOneof() {}

type isEmployeeSearch_EmailAddressOneof interface {
	isEmployeeSearch_EmailAddressOneof()
}

type EmployeeSearch_EmailAddress struct {
	// email_address
	EmailAddress string `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3,oneof"`
}

func (*EmployeeSearch_EmailAddress) isEmployeeSearch_EmailAddressOneof() {}

// Wrapper describes a basic data type for conversion of any
// other data type
type Wrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is a string identifying the type of payload
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// payload describes the payload as protobuf.any
	Payload *anypb.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{13}
}

func (x *Wrapper) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Wrapper) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Bytes makes it easier to provide
type Bytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// bytes describes the payload
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{14}
}

func (x *Bytes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Error
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// error
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employees_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_employees_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_employees_proto_rawDescGZIP(), []int{15}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_employees_proto protoreflect.FileDescriptor

var file_employees_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x15, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x10,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64,
	0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x0f,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x22,
	0x55, 0x0a, 0x16, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f,
	0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a,
	0x14, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75,
	0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x22, 0x66, 0x0a, 0x14, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x0f, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f,
	0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x0e, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x56, 0x0a, 0x15, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64,
	0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x73, 0x22, 0x7a, 0x0a, 0x15, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x51, 0x0a, 0x10, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67,
	0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x0f, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x55,
	0x0a, 0x16, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x5f,
	0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18,
	0x0a, 0x16, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x0f, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0a,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0d,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x12, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x11, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x15, 0x0a, 0x13, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x22, 0xe0, 0x01, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x64, 0x70, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x64, 0x70, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb0, 0x02, 0x0a, 0x0e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x09, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x12, 0x0a, 0x10, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x11, 0x0a,
	0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x42, 0x15, 0x0a, 0x13, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x4d, 0x0a, 0x07, 0x57, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x1d, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0xbc, 0x04, 0x0a, 0x09, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x73, 0x12, 0x70, 0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67,
	0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f,
	0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x5f, 0x72, 0x65, 0x61, 0x64, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67,
	0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x6d, 0x0a, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x5f, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x70, 0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x2c, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x70, 0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65,
	0x6f, 0x6e, 0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x69, 0x6f, 0x2d, 0x61, 0x6c, 0x65, 0x78, 0x61, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x2f,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_employees_proto_rawDescOnce sync.Once
	file_employees_proto_rawDescData = file_employees_proto_rawDesc
)

func file_employees_proto_rawDescGZIP() []byte {
	file_employees_proto_rawDescOnce.Do(func() {
		file_employees_proto_rawDescData = protoimpl.X.CompressGZIP(file_employees_proto_rawDescData)
	})
	return file_employees_proto_rawDescData
}

var file_employees_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_employees_proto_goTypes = []interface{}{
	(*EmployeeCreateRequest)(nil),  // 0: go_bludgeon_employees.EmployeeCreateRequest
	(*EmployeeCreateResponse)(nil), // 1: go_bludgeon_employees.EmployeeCreateResponse
	(*EmployeeReadRequest)(nil),    // 2: go_bludgeon_employees.EmployeeReadRequest
	(*EmployeeReadResponse)(nil),   // 3: go_bludgeon_employees.EmployeeReadResponse
	(*EmployeesReadRequest)(nil),   // 4: go_bludgeon_employees.EmployeesReadRequest
	(*EmployeesReadResponse)(nil),  // 5: go_bludgeon_employees.EmployeesReadResponse
	(*EmployeeUpdateRequest)(nil),  // 6: go_bludgeon_employees.EmployeeUpdateRequest
	(*EmployeeUpdateResponse)(nil), // 7: go_bludgeon_employees.EmployeeUpdateResponse
	(*EmployeeDeleteRequest)(nil),  // 8: go_bludgeon_employees.EmployeeDeleteRequest
	(*EmployeeDeleteResponse)(nil), // 9: go_bludgeon_employees.EmployeeDeleteResponse
	(*EmployeePartial)(nil),        // 10: go_bludgeon_employees.EmployeePartial
	(*Employee)(nil),               // 11: go_bludgeon_employees.Employee
	(*EmployeeSearch)(nil),         // 12: go_bludgeon_employees.EmployeeSearch
	(*Wrapper)(nil),                // 13: go_bludgeon_employees.Wrapper
	(*Bytes)(nil),                  // 14: go_bludgeon_employees.Bytes
	(*Error)(nil),                  // 15: go_bludgeon_employees.Error
	(*anypb.Any)(nil),              // 16: google.protobuf.Any
}
var file_employees_proto_depIdxs = []int32{
	10, // 0: go_bludgeon_employees.EmployeeCreateRequest.employee_partial:type_name -> go_bludgeon_employees.EmployeePartial
	11, // 1: go_bludgeon_employees.EmployeeCreateResponse.employee:type_name -> go_bludgeon_employees.Employee
	11, // 2: go_bludgeon_employees.EmployeeReadResponse.employee:type_name -> go_bludgeon_employees.Employee
	12, // 3: go_bludgeon_employees.EmployeesReadRequest.employee_search:type_name -> go_bludgeon_employees.EmployeeSearch
	11, // 4: go_bludgeon_employees.EmployeesReadResponse.employees:type_name -> go_bludgeon_employees.Employee
	10, // 5: go_bludgeon_employees.EmployeeUpdateRequest.employee_partial:type_name -> go_bludgeon_employees.EmployeePartial
	11, // 6: go_bludgeon_employees.EmployeeUpdateResponse.employee:type_name -> go_bludgeon_employees.Employee
	16, // 7: go_bludgeon_employees.Wrapper.payload:type_name -> google.protobuf.Any
	0,  // 8: go_bludgeon_employees.Employees.employee_create:input_type -> go_bludgeon_employees.EmployeeCreateRequest
	2,  // 9: go_bludgeon_employees.Employees.employee_read:input_type -> go_bludgeon_employees.EmployeeReadRequest
	4,  // 10: go_bludgeon_employees.Employees.employees_read:input_type -> go_bludgeon_employees.EmployeesReadRequest
	6,  // 11: go_bludgeon_employees.Employees.employee_update:input_type -> go_bludgeon_employees.EmployeeUpdateRequest
	8,  // 12: go_bludgeon_employees.Employees.employee_delete:input_type -> go_bludgeon_employees.EmployeeDeleteRequest
	1,  // 13: go_bludgeon_employees.Employees.employee_create:output_type -> go_bludgeon_employees.EmployeeCreateResponse
	3,  // 14: go_bludgeon_employees.Employees.employee_read:output_type -> go_bludgeon_employees.EmployeeReadResponse
	5,  // 15: go_bludgeon_employees.Employees.employees_read:output_type -> go_bludgeon_employees.EmployeesReadResponse
	7,  // 16: go_bludgeon_employees.Employees.employee_update:output_type -> go_bludgeon_employees.EmployeeUpdateResponse
	9,  // 17: go_bludgeon_employees.Employees.employee_delete:output_type -> go_bludgeon_employees.EmployeeDeleteResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_employees_proto_init() }
func file_employees_proto_init() {
	if File_employees_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_employees_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeesReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeesReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeePartial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employees_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_employees_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*EmployeePartial_FirstName)(nil),
		(*EmployeePartial_LastName)(nil),
		(*EmployeePartial_EmailAddress)(nil),
	}
	file_employees_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*EmployeeSearch_FirstName)(nil),
		(*EmployeeSearch_LastName)(nil),
		(*EmployeeSearch_EmailAddress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_employees_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employees_proto_goTypes,
		DependencyIndexes: file_employees_proto_depIdxs,
		MessageInfos:      file_employees_proto_msgTypes,
	}.Build()
	File_employees_proto = out.File
	file_employees_proto_rawDesc = nil
	file_employees_proto_goTypes = nil
	file_employees_proto_depIdxs = nil
}
