//
//go_bludgeon_timers defines a set of types for use with the timers service

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: timeslices.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeSliceCreateRequest
type TimeSliceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slice_partial
	TimeSlicePartial *TimeSlicePartial `protobuf:"bytes,1,opt,name=time_slice_partial,json=timeSlicePartial,proto3" json:"time_slice_partial,omitempty"`
}

func (x *TimeSliceCreateRequest) Reset() {
	*x = TimeSliceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceCreateRequest) ProtoMessage() {}

func (x *TimeSliceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceCreateRequest.ProtoReflect.Descriptor instead.
func (*TimeSliceCreateRequest) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSliceCreateRequest) GetTimeSlicePartial() *TimeSlicePartial {
	if x != nil {
		return x.TimeSlicePartial
	}
	return nil
}

// TimeSliceCreateResponse
type TimeSliceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slice
	TimeSlice *TimeSlice `protobuf:"bytes,1,opt,name=time_slice,json=timeSlice,proto3" json:"time_slice,omitempty"`
}

func (x *TimeSliceCreateResponse) Reset() {
	*x = TimeSliceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceCreateResponse) ProtoMessage() {}

func (x *TimeSliceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceCreateResponse.ProtoReflect.Descriptor instead.
func (*TimeSliceCreateResponse) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSliceCreateResponse) GetTimeSlice() *TimeSlice {
	if x != nil {
		return x.TimeSlice
	}
	return nil
}

// TimeSliceReadRequest
type TimeSliceReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TimeSliceReadRequest) Reset() {
	*x = TimeSliceReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceReadRequest) ProtoMessage() {}

func (x *TimeSliceReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceReadRequest.ProtoReflect.Descriptor instead.
func (*TimeSliceReadRequest) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSliceReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TimeSliceReadResponse
type TimeSliceReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slice
	TimeSlice *TimeSlice `protobuf:"bytes,1,opt,name=time_slice,json=timeSlice,proto3" json:"time_slice,omitempty"`
}

func (x *TimeSliceReadResponse) Reset() {
	*x = TimeSliceReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceReadResponse) ProtoMessage() {}

func (x *TimeSliceReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceReadResponse.ProtoReflect.Descriptor instead.
func (*TimeSliceReadResponse) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{3}
}

func (x *TimeSliceReadResponse) GetTimeSlice() *TimeSlice {
	if x != nil {
		return x.TimeSlice
	}
	return nil
}

// TimeSliceUpdateRequest
type TimeSliceUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// time_slice_partial
	TimeSlicePartial *TimeSlicePartial `protobuf:"bytes,2,opt,name=time_slice_partial,json=timeSlicePartial,proto3" json:"time_slice_partial,omitempty"`
}

func (x *TimeSliceUpdateRequest) Reset() {
	*x = TimeSliceUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceUpdateRequest) ProtoMessage() {}

func (x *TimeSliceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceUpdateRequest.ProtoReflect.Descriptor instead.
func (*TimeSliceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSliceUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeSliceUpdateRequest) GetTimeSlicePartial() *TimeSlicePartial {
	if x != nil {
		return x.TimeSlicePartial
	}
	return nil
}

// TimeSliceUpdateResponse
type TimeSliceUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slice
	TimeSlice *TimeSlice `protobuf:"bytes,1,opt,name=time_slice,json=timeSlice,proto3" json:"time_slice,omitempty"`
}

func (x *TimeSliceUpdateResponse) Reset() {
	*x = TimeSliceUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceUpdateResponse) ProtoMessage() {}

func (x *TimeSliceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceUpdateResponse.ProtoReflect.Descriptor instead.
func (*TimeSliceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSliceUpdateResponse) GetTimeSlice() *TimeSlice {
	if x != nil {
		return x.TimeSlice
	}
	return nil
}

// TimeSliceDeleteRequest
type TimeSliceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TimeSliceDeleteRequest) Reset() {
	*x = TimeSliceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceDeleteRequest) ProtoMessage() {}

func (x *TimeSliceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceDeleteRequest.ProtoReflect.Descriptor instead.
func (*TimeSliceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{6}
}

func (x *TimeSliceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TimeSliceDeleteResponse
type TimeSliceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimeSliceDeleteResponse) Reset() {
	*x = TimeSliceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceDeleteResponse) ProtoMessage() {}

func (x *TimeSliceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceDeleteResponse.ProtoReflect.Descriptor instead.
func (*TimeSliceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{7}
}

// TimeSlicesReadRequest
type TimeSlicesReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slice_search
	TimeSliceSearch *TimeSliceSearch `protobuf:"bytes,1,opt,name=time_slice_search,json=timeSliceSearch,proto3" json:"time_slice_search,omitempty"`
}

func (x *TimeSlicesReadRequest) Reset() {
	*x = TimeSlicesReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlicesReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlicesReadRequest) ProtoMessage() {}

func (x *TimeSlicesReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlicesReadRequest.ProtoReflect.Descriptor instead.
func (*TimeSlicesReadRequest) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{8}
}

func (x *TimeSlicesReadRequest) GetTimeSliceSearch() *TimeSliceSearch {
	if x != nil {
		return x.TimeSliceSearch
	}
	return nil
}

// TimeSlicesReadResponse
type TimeSlicesReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// time_slices
	TimeSlices []*TimeSlice `protobuf:"bytes,1,rep,name=time_slices,json=timeSlices,proto3" json:"time_slices,omitempty"`
}

func (x *TimeSlicesReadResponse) Reset() {
	*x = TimeSlicesReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlicesReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlicesReadResponse) ProtoMessage() {}

func (x *TimeSlicesReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlicesReadResponse.ProtoReflect.Descriptor instead.
func (*TimeSlicesReadResponse) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{9}
}

func (x *TimeSlicesReadResponse) GetTimeSlices() []*TimeSlice {
	if x != nil {
		return x.TimeSlices
	}
	return nil
}

// TimeSlicePartial
type TimeSlicePartial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// timer_id_oneof
	//
	// Types that are assignable to TimerIdOneof:
	//	*TimeSlicePartial_TimerId
	TimerIdOneof isTimeSlicePartial_TimerIdOneof `protobuf_oneof:"timer_id_oneof"`
	// completed_oneof
	//
	// Types that are assignable to CompletedOneof:
	//	*TimeSlicePartial_Completed
	CompletedOneof isTimeSlicePartial_CompletedOneof `protobuf_oneof:"completed_oneof"`
	// start_oneof
	//
	// Types that are assignable to StartOneof:
	//	*TimeSlicePartial_Start
	StartOneof isTimeSlicePartial_StartOneof `protobuf_oneof:"start_oneof"`
	// finish_oneof
	//
	// Types that are assignable to FinishOneof:
	//	*TimeSlicePartial_Finish
	FinishOneof isTimeSlicePartial_FinishOneof `protobuf_oneof:"finish_oneof"`
}

func (x *TimeSlicePartial) Reset() {
	*x = TimeSlicePartial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlicePartial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlicePartial) ProtoMessage() {}

func (x *TimeSlicePartial) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlicePartial.ProtoReflect.Descriptor instead.
func (*TimeSlicePartial) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{10}
}

func (m *TimeSlicePartial) GetTimerIdOneof() isTimeSlicePartial_TimerIdOneof {
	if m != nil {
		return m.TimerIdOneof
	}
	return nil
}

func (x *TimeSlicePartial) GetTimerId() string {
	if x, ok := x.GetTimerIdOneof().(*TimeSlicePartial_TimerId); ok {
		return x.TimerId
	}
	return ""
}

func (m *TimeSlicePartial) GetCompletedOneof() isTimeSlicePartial_CompletedOneof {
	if m != nil {
		return m.CompletedOneof
	}
	return nil
}

func (x *TimeSlicePartial) GetCompleted() bool {
	if x, ok := x.GetCompletedOneof().(*TimeSlicePartial_Completed); ok {
		return x.Completed
	}
	return false
}

func (m *TimeSlicePartial) GetStartOneof() isTimeSlicePartial_StartOneof {
	if m != nil {
		return m.StartOneof
	}
	return nil
}

func (x *TimeSlicePartial) GetStart() int64 {
	if x, ok := x.GetStartOneof().(*TimeSlicePartial_Start); ok {
		return x.Start
	}
	return 0
}

func (m *TimeSlicePartial) GetFinishOneof() isTimeSlicePartial_FinishOneof {
	if m != nil {
		return m.FinishOneof
	}
	return nil
}

func (x *TimeSlicePartial) GetFinish() int64 {
	if x, ok := x.GetFinishOneof().(*TimeSlicePartial_Finish); ok {
		return x.Finish
	}
	return 0
}

type isTimeSlicePartial_TimerIdOneof interface {
	isTimeSlicePartial_TimerIdOneof()
}

type TimeSlicePartial_TimerId struct {
	// timer_id
	TimerId string `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3,oneof"`
}

func (*TimeSlicePartial_TimerId) isTimeSlicePartial_TimerIdOneof() {}

type isTimeSlicePartial_CompletedOneof interface {
	isTimeSlicePartial_CompletedOneof()
}

type TimeSlicePartial_Completed struct {
	// completed_oneof
	Completed bool `protobuf:"varint,2,opt,name=completed,proto3,oneof"`
}

func (*TimeSlicePartial_Completed) isTimeSlicePartial_CompletedOneof() {}

type isTimeSlicePartial_StartOneof interface {
	isTimeSlicePartial_StartOneof()
}

type TimeSlicePartial_Start struct {
	// start
	Start int64 `protobuf:"varint,3,opt,name=start,proto3,oneof"`
}

func (*TimeSlicePartial_Start) isTimeSlicePartial_StartOneof() {}

type isTimeSlicePartial_FinishOneof interface {
	isTimeSlicePartial_FinishOneof()
}

type TimeSlicePartial_Finish struct {
	// finish
	Finish int64 `protobuf:"varint,4,opt,name=finish,proto3,oneof"`
}

func (*TimeSlicePartial_Finish) isTimeSlicePartial_FinishOneof() {}

// TimeSlice
type TimeSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// completed
	Completed bool `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	// start
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// finish
	Finish int64 `protobuf:"varint,3,opt,name=finish,proto3" json:"finish,omitempty"`
	// elapsed_time
	ElapsedTime int64 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	// id
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// timer_id
	TimerId string `protobuf:"bytes,6,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	// last_updated
	LastUpdated int64 `protobuf:"varint,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// last_updated_by
	LastUpdatedBy string `protobuf:"bytes,8,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by,omitempty"`
	// version
	Version int32 `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TimeSlice) Reset() {
	*x = TimeSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlice) ProtoMessage() {}

func (x *TimeSlice) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlice.ProtoReflect.Descriptor instead.
func (*TimeSlice) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{11}
}

func (x *TimeSlice) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TimeSlice) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeSlice) GetFinish() int64 {
	if x != nil {
		return x.Finish
	}
	return 0
}

func (x *TimeSlice) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *TimeSlice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeSlice) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimeSlice) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *TimeSlice) GetLastUpdatedBy() string {
	if x != nil {
		return x.LastUpdatedBy
	}
	return ""
}

func (x *TimeSlice) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// TimeSliceSearch
type TimeSliceSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// completed_oneof
	//
	// Types that are assignable to CompletedOneof:
	//	*TimeSliceSearch_Completed
	CompletedOneof isTimeSliceSearch_CompletedOneof `protobuf_oneof:"completed_oneof"`
	// timer_id_oneof
	//
	// Types that are assignable to TimerIdOneof:
	//	*TimeSliceSearch_TimerId
	TimerIdOneof isTimeSliceSearch_TimerIdOneof `protobuf_oneof:"timer_id_oneof"`
	// timer_ids
	TimerIds []string `protobuf:"bytes,3,rep,name=timer_ids,json=timerIds,proto3" json:"timer_ids,omitempty"`
	// ids
	Ids []string `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *TimeSliceSearch) Reset() {
	*x = TimeSliceSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslices_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSliceSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSliceSearch) ProtoMessage() {}

func (x *TimeSliceSearch) ProtoReflect() protoreflect.Message {
	mi := &file_timeslices_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSliceSearch.ProtoReflect.Descriptor instead.
func (*TimeSliceSearch) Descriptor() ([]byte, []int) {
	return file_timeslices_proto_rawDescGZIP(), []int{12}
}

func (m *TimeSliceSearch) GetCompletedOneof() isTimeSliceSearch_CompletedOneof {
	if m != nil {
		return m.CompletedOneof
	}
	return nil
}

func (x *TimeSliceSearch) GetCompleted() bool {
	if x, ok := x.GetCompletedOneof().(*TimeSliceSearch_Completed); ok {
		return x.Completed
	}
	return false
}

func (m *TimeSliceSearch) GetTimerIdOneof() isTimeSliceSearch_TimerIdOneof {
	if m != nil {
		return m.TimerIdOneof
	}
	return nil
}

func (x *TimeSliceSearch) GetTimerId() string {
	if x, ok := x.GetTimerIdOneof().(*TimeSliceSearch_TimerId); ok {
		return x.TimerId
	}
	return ""
}

func (x *TimeSliceSearch) GetTimerIds() []string {
	if x != nil {
		return x.TimerIds
	}
	return nil
}

func (x *TimeSliceSearch) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type isTimeSliceSearch_CompletedOneof interface {
	isTimeSliceSearch_CompletedOneof()
}

type TimeSliceSearch_Completed struct {
	// completed
	Completed bool `protobuf:"varint,1,opt,name=completed,proto3,oneof"`
}

func (*TimeSliceSearch_Completed) isTimeSliceSearch_CompletedOneof() {}

type isTimeSliceSearch_TimerIdOneof interface {
	isTimeSliceSearch_TimerIdOneof()
}

type TimeSliceSearch_TimerId struct {
	// timer_id
	TimerId string `protobuf:"bytes,2,opt,name=timer_id,json=timerId,proto3,oneof"`
}

func (*TimeSliceSearch_TimerId) isTimeSliceSearch_TimerIdOneof() {}

var File_timeslices_proto protoreflect.FileDescriptor

var file_timeslices_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x22, 0x6c, 0x0a, 0x16, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x52, 0x0a, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67,
	0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x61, 0x6c, 0x22, 0x57, 0x0a, 0x17, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a,
	0x14, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x22, 0x7c, 0x0a, 0x16,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x52, 0x0a, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73,
	0x6c, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x57, 0x0a, 0x17, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c,
	0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x62,
	0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x68, 0x0a, 0x15, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x4f, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67,
	0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x22, 0x58, 0x0a, 0x16, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x22, 0xc5, 0x01, 0x0a,
	0x10, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x12, 0x1b, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x01, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x42, 0x10, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6f, 0x6e, 0x65,
	0x6f, 0x66, 0x42, 0x11, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0d, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0e, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x22, 0x8a, 0x02, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x42, 0x11, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x42, 0x10, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x32, 0xb3, 0x04, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x6c, 0x69, 0x63, 0x65, 0x73, 0x12, 0x6e, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c,
	0x69, 0x63, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x5f,
	0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64,
	0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x6c, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c,
	0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x12, 0x28, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c,
	0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6e, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6e, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6b, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x29, 0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x67, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x74, 0x6f, 0x6e,
	0x69, 0x6f, 0x2d, 0x61, 0x6c, 0x65, 0x78, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d,
	0x62, 0x6c, 0x75, 0x64, 0x67, 0x65, 0x6f, 0x6e, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeslices_proto_rawDescOnce sync.Once
	file_timeslices_proto_rawDescData = file_timeslices_proto_rawDesc
)

func file_timeslices_proto_rawDescGZIP() []byte {
	file_timeslices_proto_rawDescOnce.Do(func() {
		file_timeslices_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeslices_proto_rawDescData)
	})
	return file_timeslices_proto_rawDescData
}

var file_timeslices_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_timeslices_proto_goTypes = []interface{}{
	(*TimeSliceCreateRequest)(nil),  // 0: go_bludgeon_timers.TimeSliceCreateRequest
	(*TimeSliceCreateResponse)(nil), // 1: go_bludgeon_timers.TimeSliceCreateResponse
	(*TimeSliceReadRequest)(nil),    // 2: go_bludgeon_timers.TimeSliceReadRequest
	(*TimeSliceReadResponse)(nil),   // 3: go_bludgeon_timers.TimeSliceReadResponse
	(*TimeSliceUpdateRequest)(nil),  // 4: go_bludgeon_timers.TimeSliceUpdateRequest
	(*TimeSliceUpdateResponse)(nil), // 5: go_bludgeon_timers.TimeSliceUpdateResponse
	(*TimeSliceDeleteRequest)(nil),  // 6: go_bludgeon_timers.TimeSliceDeleteRequest
	(*TimeSliceDeleteResponse)(nil), // 7: go_bludgeon_timers.TimeSliceDeleteResponse
	(*TimeSlicesReadRequest)(nil),   // 8: go_bludgeon_timers.TimeSlicesReadRequest
	(*TimeSlicesReadResponse)(nil),  // 9: go_bludgeon_timers.TimeSlicesReadResponse
	(*TimeSlicePartial)(nil),        // 10: go_bludgeon_timers.TimeSlicePartial
	(*TimeSlice)(nil),               // 11: go_bludgeon_timers.TimeSlice
	(*TimeSliceSearch)(nil),         // 12: go_bludgeon_timers.TimeSliceSearch
}
var file_timeslices_proto_depIdxs = []int32{
	10, // 0: go_bludgeon_timers.TimeSliceCreateRequest.time_slice_partial:type_name -> go_bludgeon_timers.TimeSlicePartial
	11, // 1: go_bludgeon_timers.TimeSliceCreateResponse.time_slice:type_name -> go_bludgeon_timers.TimeSlice
	11, // 2: go_bludgeon_timers.TimeSliceReadResponse.time_slice:type_name -> go_bludgeon_timers.TimeSlice
	10, // 3: go_bludgeon_timers.TimeSliceUpdateRequest.time_slice_partial:type_name -> go_bludgeon_timers.TimeSlicePartial
	11, // 4: go_bludgeon_timers.TimeSliceUpdateResponse.time_slice:type_name -> go_bludgeon_timers.TimeSlice
	12, // 5: go_bludgeon_timers.TimeSlicesReadRequest.time_slice_search:type_name -> go_bludgeon_timers.TimeSliceSearch
	11, // 6: go_bludgeon_timers.TimeSlicesReadResponse.time_slices:type_name -> go_bludgeon_timers.TimeSlice
	0,  // 7: go_bludgeon_timers.TimeSlices.time_slice_create:input_type -> go_bludgeon_timers.TimeSliceCreateRequest
	2,  // 8: go_bludgeon_timers.TimeSlices.time_slice_read:input_type -> go_bludgeon_timers.TimeSliceReadRequest
	4,  // 9: go_bludgeon_timers.TimeSlices.time_slice_update:input_type -> go_bludgeon_timers.TimeSliceUpdateRequest
	6,  // 10: go_bludgeon_timers.TimeSlices.time_slice_delete:input_type -> go_bludgeon_timers.TimeSliceDeleteRequest
	8,  // 11: go_bludgeon_timers.TimeSlices.time_slices_read:input_type -> go_bludgeon_timers.TimeSlicesReadRequest
	1,  // 12: go_bludgeon_timers.TimeSlices.time_slice_create:output_type -> go_bludgeon_timers.TimeSliceCreateResponse
	3,  // 13: go_bludgeon_timers.TimeSlices.time_slice_read:output_type -> go_bludgeon_timers.TimeSliceReadResponse
	5,  // 14: go_bludgeon_timers.TimeSlices.time_slice_update:output_type -> go_bludgeon_timers.TimeSliceUpdateResponse
	7,  // 15: go_bludgeon_timers.TimeSlices.time_slice_delete:output_type -> go_bludgeon_timers.TimeSliceDeleteResponse
	9,  // 16: go_bludgeon_timers.TimeSlices.time_slices_read:output_type -> go_bludgeon_timers.TimeSlicesReadResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_timeslices_proto_init() }
func file_timeslices_proto_init() {
	if File_timeslices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timeslices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlicesReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlicesReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlicePartial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslices_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSliceSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_timeslices_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*TimeSlicePartial_TimerId)(nil),
		(*TimeSlicePartial_Completed)(nil),
		(*TimeSlicePartial_Start)(nil),
		(*TimeSlicePartial_Finish)(nil),
	}
	file_timeslices_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*TimeSliceSearch_Completed)(nil),
		(*TimeSliceSearch_TimerId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeslices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeslices_proto_goTypes,
		DependencyIndexes: file_timeslices_proto_depIdxs,
		MessageInfos:      file_timeslices_proto_msgTypes,
	}.Build()
	File_timeslices_proto = out.File
	file_timeslices_proto_rawDesc = nil
	file_timeslices_proto_goTypes = nil
	file_timeslices_proto_depIdxs = nil
}
