version: "3"
services:
  postgres:
    container_name: "postgres"
    hostname: "postgres"
    image: ghcr.io/antonio-alexander/bludgeon-database-postgres:latest
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bludgeon
      POSTGRES_DB: bludgeon
      POSTGRES_PASSWORD: bludgeon
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: ghcr.io/antonio-alexander/bludgeon-database-mysql:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bludgeon
      MYSQL_DATABASE: bludgeon
      MYSQL_USER: bludgeon
      MYSQL_PASSWORD: bludgeon
  bludgeon-server:
    container_name: "bludgeon-server"
    hostname: "bludgeon-server"
    image: ghcr.io/antonio-alexander/bludgeon-server:latest
    restart: "always"
    build:
      context: ./
      dockerfile: ./cmd/bludgeon-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_ADDRESS: "mysql" #"postgres"
      DATABASE_PORT: "3306" #"5432"
      BLUDGEON_SERVER_TYPE: "rest"
      BLUDGEON_META_TYPE: "file"
      BLUDGEON_REST_ADDRESS: "0.0.0.0"
      BLUDGEON_REST_PORT: "8080"
      BLUDGEON_META__FILE: "data/bludgeon.json"
    volumes:
      - ./cmd/config:/app/config
      - ./cmd/data:/app/data
