package errors

import "github.com/pkg/errors"

//Error represents any error that can be generated by bludgeon
// swagger:model Error
type Error struct {
	// Error contains the text of any failed operation
	// example: employee not found
	Error string `json:"error"`
}

func NewError(err error) Error {
	if err != nil {
		return Error{
			Error: err.Error(),
		}
	}
	return Error{}
}

type ErrNotFound struct {
	error
}

func NewNotFound(err string) error {
	return &ErrNotFound{
		error: errors.New(err),
	}
}

type ErrNotCreated struct {
	error
}

func NewNotCreated(err string) error {
	return &ErrNotUpdated{
		error: errors.New(err),
	}
}

type ErrNotUpdated struct {
	error
}

func NewNotupdated(err string) error {
	return &ErrNotUpdated{
		error: errors.New(err),
	}
}

type ErrConflict struct {
	error
}

func NewConflict(err string) error {
	return &ErrConflict{
		error: errors.New(err),
	}
}
