version: "3"
services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: ghcr.io/antonio-alexander/go-bludgeon-mysql:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bludgeon
      MYSQL_DATABASE: bludgeon
      MYSQL_USER: bludgeon
      MYSQL_PASSWORD: bludgeon

  employees:
    container_name: "employees"
    hostname: "employees"
    image: ghcr.io/antonio-alexander/go-bludgeon-employees:latest
    depends_on:
      - mysql
    restart: "always"
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./cmd/service/Dockerfile
      args:
        - PLATFORM=linux/amd64
        - GO_ARCH=amd64
        # - GO_ARCH=arm
        # - GO_ARM=7
    environment:
      BLUDGEON_SERVICE_TYPE: "rest"
      BLUDGEON_META_TYPE: "mysql"
      BLUDGEON_REST_ADDRESS: "0.0.0.0"
      BLUDGEON_REST_PORT: "8080"
      BLUDGEON_META__FILE: "data/bludgeon.json"
      BLUDGEON_ALLOWED_ORIGINS: "http://host.docker.internal"
      BLUDGEON_CORS_DEBUG: "true"
      DATABASE_HOST: "mysql"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "bludgeon"
      DATABASE_USER: "bludgeon"
      DATABASE_PASSWORD: "bludgeon"
