version: '3'
services:
  server:
      container_name: "database"
      image: mariadb:latest
      restart: "always"
      ports:
        - "3306:3306"
  server:
    container_name: "bludgeon-server"
    restart: "always"
    build:
      context: ../
      dockerfile: ./cmd/server_rest/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - server-data: /app/data
      - server-config: /app/config
#  client:
volumes:
  - server-data
  - server-config
  - client-data
  - client-config