#---------------------------------------------------------------------------------------------------
# bludgeon-employee-swagger [Dockerfile]
# 
# Reference: https://stackoverflow.com/questions/63178036/how-to-find-commit-hash-from-within-a-running-docker-image
# commit: git rev-parse HEAD
# 
# https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
# branch: git rev-parse --abbrev-ref HEAD
# 
#---------------------------------------------------------------------------------------------------

ARG GIT_BRANCH=no_git_branch_provided
ARG GIT_COMMIT=no_git_commit_provided
ARG PLATFORM=linux/amd64
ARG GO_ARCH=amd64
ARG GO_ARM=7

FROM golang:alpine AS build

ARG GO_ARCH
ARG GO_ARM
ARG GIT_BRANCH
ARG GIT_COMMIT

RUN \
    apk add gcc g++ \
    && env GOARCH=${GO_ARCH} GOARM=${GO_ARM} GOOS=linux CGO_ENABLED=1 \
    go install github.com/go-swagger/go-swagger/cmd/swagger@v0.29.0 

COPY . /go/src/github.com/antonio-alexander/go-bludgeon/employee 

WORKDIR /go/src/github.com/antonio-alexander/go-bludgeon/employee/cmd/service

RUN swagger generate spec -o ./swagger.yaml --scan-models

LABEL antonio-alexander.git.branch=${GIT_BRANCH}
LABEL antonio-alexander.git.commit=${GIT_COMMIT}
LABEL org.opencontainers.image.source=https://github.com/antonio-alexander/go-bludgeon

EXPOSE 8080

CMD swagger serve -F=swagger swagger.yaml -p 8080 --no-open