version: "3"

services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: ghcr.io/antonio-alexander/go-bludgeon-mysql:latest
    restart: "always"
    ports:
      - "3306:3306"
    build:
      context: ./
      dockerfile: ./cmd/Dockerfile
      args:
        - PLATFORM=linux/amd64
        # - PLATFORM=linux/arm/v7
    environment:
      BLUDGEON_MICROSERVICE: true
