#---------------------------------------------------------------------------------------------------
# bludgeon-employee [Dockerfile.Debug]
# 
# Reference: https://stackoverflow.com/questions/63178036/how-to-find-commit-hash-from-within-a-running-docker-image
# commit: git rev-parse HEAD
# 
# https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
# branch: git rev-parse --abbrev-ref HEAD
# 
# https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63
# The GOOS will always be linux, but in case you were curious
#
#---------------------------------------------------------------------------------------------------

ARG GIT_BRANCH=no_git_branch_provided
ARG GIT_COMMIT=no_git_commit_provided
ARG PLATFORM=linux/amd64
ARG GO_ARCH=amd64
ARG GO_ARM=7

FROM golang:alpine AS build

ARG GIT_BRANCH
ARG GIT_COMMIT
ARG GO_ARCH
ARG GO_ARM

WORKDIR /go/src/go-bludgeon/employee

COPY . /go/src/go-bludgeon/employee

RUN \
    apk add --no-cache ca-certificates jq dpkg gcc git musl-dev \
    && go get github.com/go-delve/delve/cmd/dlv@v1.8.3

RUN \
    VERSION=`cat /go/src/go-bludgeon/employee/version.json | jq '.Version' | sed 's/"//g'` \
    && cd cmd/service \
    && env GOARCH=${GO_ARCH} GOARM=${GO_ARM} GOOS=linux go build -gcflags "all=-N -l" -ldflags \
    "-X github.com/antonio-alexander/go-bludgeon/employee/cmd/service/internal.Version=${VERSION} \
    -X github.com/antonio-alexander/go-bludgeon/employee/cmd/service/internal.GitCommit=${GIT_COMMIT} \
    -X github.com/antonio-alexander/go-bludgeon/employee/cmd/service/internal.GitBranch=${GIT_BRANCH}" \
    -o bludgeon-employee \
    && chmod +X bludgeon-employee

FROM --platform=${PLATFORM} alpine:latest

ARG GIT_BRANCH
ARG GIT_COMMIT

WORKDIR /app

COPY --from=build /go/src/go-bludgeon/employee/cmd/service/bludgeon-employee /app/bludgeon-employee
COPY --from=build /go/src/go-bludgeon/employee/cmd/service/config/bludgeon_server_config-default.json /app/config/bludgeon_server_config-default.json

LABEL antonio-alexander.git.branch=${GIT_BRANCH}-debug
LABEL antonio-alexander.git.commit=${GIT_COMMIT}-debug
LABEL org.opencontainers.image.source=https://github.com/antonio-alexander/go-bludgeon

EXPOSE 8080 2345

CMD dlv exec /app/bludgeon-employee --headless --listen=":2345" --log --api-version=2 --check-go-version=false
