version: "3"
services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: ghcr.io/antonio-alexander/go-bludgeon-mysql:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-bludgeon}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"

  kafka:
    hostname: kafka
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    healthcheck:
      test: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9093 --list"
      start_period: 0s
      interval: 30s
      timeout: 2m
      retries: 10
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
