name: "Proto Lint"
description: |
  Executes the proto-lint command
  Example usage:
    - uses: nationaloilwellvarco/max-core/.github/actions/proto_lint@v1
        with:
          folder-name: healthcheck
          golang-version: 1.21
          golang-cache-dependency-paths: ./healthcheck/go.sum
inputs:
  folder-name:
    description: "folder name to execute commands from"
    required: true
  golang-version:
    description: "the Go version to use for Go related functions"
    required: true
  golang-cache-dependency-paths:
    description: "all of the dependency paths (go.mod) to cache"
    required: true
  proto-pattern:
    description: "the pattern for proto files to Lint"
    default: ./data/pb/*.proto
  proto-lint-version:
    description: "the version of protolint to use"
  proto-lint-logging-level:
    description: "the logging level for proto lint"
    default: error
  github-token:
    description: "the github token"
    required: true
outputs:
  proto_lint_log_file:
    description: "proto_lint_log_file"
    value: ${{ steps.proto_lint.outputs.proto_lint_log_file }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.golang-version }}
        cache-dependency-path: ${{ inputs.golang-cache-dependency-paths }}
    - shell: bash
      working-directory: ${{ inputs.folder-name }}
      id: proto_lint
      run: |
        proto_lint_log_file=$PWD/tmp/test_${{ inputs.folder-name }}.log
        echo test log file: $proto_lint_log_file
        echo "proto_lint_log_file=$proto_lint_log_file" >> $GITHUB_OUTPUT
        go install github.com/yoheimuta/protolint/cmd/protolint@v${{ inputs.proto-lint-version }}
        protolint -output_file=$proto_lint_log_file -config_path=./.protolint.yaml ${{ inputs.proto-pattern }}
