name: docs_push

on:
  push:
    branches:
      - main
    paths:
      - "timers/**"
      - "employees/**"
      - "changes/**"
      - "healthcheck/**"
      - "cmd/docs/**"

env:
  GO_VERSION: "1.21"
  SWAGGER_REPO: https://github.com/swagger-api/swagger-ui
  SWAGGER_TAG: v4.15.5

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  go_mod_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/go_mod_cache@v1
        with:
          golang-version: ${{ env.GO_VERSION }}
          golang-cache-dependency-paths: |
            healthcheck/go.sum
            changes/go.sum
            timers/go.sum
            employees/go.sum

  validate_swagger_healthcheck:
    runs-on: ubuntu-latest
    needs: [go_mod_cache]
    permissions:
      contents: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/swagger_validate@v1
        with:
          folder-name: ./healthcheck
          golang-version: ${{ env.GO_VERSION }}
          golang-cache-dependency-paths: ./healthcheck/go.sum
      - run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/healthcheck/tmp/swagger.json /tmp/swagger-healthcheck.json
      - uses: actions/upload-artifact@v4
        with:
          name: validate_swagger_healthcheck
          path: |
            /tmp/swagger-healthcheck.json

  validate_swagger_changes:
    runs-on: ubuntu-latest
    needs: [go_mod_cache]
    permissions:
      contents: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/swagger_validate@v1
        with:
          folder-name: ./changes
          golang-version: ${{ env.GO_VERSION }}
          golang-cache-dependency-paths: ./changes/go.sum
      - run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/changes/tmp/swagger.json /tmp/swagger-changes.json
      - uses: actions/upload-artifact@v4
        with:
          name: validate_swagger_changes
          path: |
            /tmp/swagger-changes.json

  validate_swagger_timers:
    runs-on: ubuntu-latest
    needs: [go_mod_cache]
    permissions:
      contents: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/swagger_validate@v1
        with:
          folder-name: ./timers
          golang-version: ${{ env.GO_VERSION }}
          golang-cache-dependency-paths: ./timers/go.sum
      - run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/timers/tmp/swagger.json /tmp/swagger-timers.json
      - uses: actions/upload-artifact@v4
        with:
          name: validate_swagger_timers
          path: |
            /tmp/swagger-timers.json

  validate_swagger_employees:
    runs-on: ubuntu-latest
    needs: [go_mod_cache]
    permissions:
      contents: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/swagger_validate@v1
        with:
          folder-name: ./employees
          golang-version: ${{ env.GO_VERSION }}
          golang-cache-dependency-paths: ./employees/go.sum
      - run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/employees/tmp/swagger.json /tmp/swagger-employees.json
      - uses: actions/upload-artifact@v4
        with:
          name: validate_swagger_employees
          path: |
            /tmp/swagger-employees.json

  github_pages_build:
    needs:
      [
        validate_swagger_changes,
        validate_swagger_employees,
        validate_swagger_timers,
        validate_swagger_healthcheck,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: validate_swagger_changes
          path: /tmp
      - uses: actions/download-artifact@v4
        with:
          name: validate_swagger_employees
          path: /tmp
      - uses: actions/download-artifact@v4
        with:
          name: validate_swagger_timers
          path: /tmp
      - uses: actions/download-artifact@v4
        with:
          name: validate_swagger_healthcheck
          path: /tmp
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: |
          git -c advice.detachedHead=false clone --depth 1 --branch "${{ env.SWAGGER_TAG }}" "${{ env.SWAGGER_REPO }}" ./tmp/swagger-ui
          mkdir ./tmp/swagger
          cp -r ./tmp/swagger-ui/dist ./tmp/swagger/dist
          cp ./cmd/docs/swagger/index.html ./tmp/swagger
          cp ./cmd/docs/swagger/swagger-initializer.js ./tmp/swagger/dist/swagger-initializer.js
          cp /tmp/swagger-timers.json ./tmp/swagger/swagger-timers.json
          cp /tmp/swagger-employees.json ./tmp/swagger/swagger-employees.json
          cp /tmp/swagger-changes.json ./tmp/swagger/swagger-changes.json
          cp /tmp/swagger-healthcheck.json ./tmp/swagger/swagger-healthcheck.json
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./tmp/swagger
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3

  github_pages_deploy:
    needs: [github_pages_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
