name: docs_push

on:
  push:
    branches:
      - main
    paths:
      - "timers/**"
      - "employees/**"
      - "changes/**"
      - "cmd/docs/**"
      - ".github/workflows/docs_push.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  environment:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}
    steps:
      - name: Get git source
        run: |
          git_source=`echo $GITHUB_REF | sed 's/refs\/heads\///'`
          git_source=`echo $git_source | sed 's/refs\/tags\///'`
          git_source=`echo $git_source | sed 's/refs\\///'`
          echo $git_source
          echo "git_source=$git_source" >> $GITHUB_ENV
      - name: Get git SHA
        run: |
          git_sha=`echo $GITHUB_SHA`
          echo $git_sha
          echo "git_sha=$git_sha" >> $GITHUB_ENV
      - name: Generate build artifacts
        run: |
          mkdir -p /tmp
          echo ${{ env.git_source }} >> /tmp/git_source
          echo ${{ env.git_sha }} >> /tmp/git_sha
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/git_source
            /tmp/git_sha

  validate_swagger_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Validate swagger spec
        run: |
          cd /home/runner/work/go-bludgeon/go-bludgeon/changes
          go mod download
          make validate-swagger
      - name: Generate build artifacts
        run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/changes/tmp/swagger.json /tmp/swagger-changes.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/swagger-changes.json

  validate_swagger_timers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Validate swagger spec
        run: |
          cd /home/runner/work/go-bludgeon/go-bludgeon/timers
          go mod download
          make validate-swagger
      - name: Generate build artifacts
        run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/timers/tmp/swagger.json /tmp/swagger-timers.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/swagger-timers.json

  validate_swagger_employees:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Validate swagger spec
        run: |
          cd /home/runner/work/go-bludgeon/go-bludgeon/employees
          go mod download
          make validate-swagger
      - name: Generate build artifacts
        run: |
          mkdir -p /tmp
          cp /home/runner/work/go-bludgeon/go-bludgeon/employees/tmp/swagger.json /tmp/swagger-employees.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/swagger-employees.json

  docker_build_images:
    needs:
      [
        environment,
        validate_swagger_changes,
        validate_swagger_employees,
        validate_swagger_timers,
      ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PLATFORM_AMD64: linux/amd64
      PLATFORM_ARMV7: linux/arm/v7
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp
      - name: Get environment
        run: |
          git_source=`cat /tmp/git_source`
          echo "git_source=$git_source" >> $GITHUB_ENV
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build docker images
        run: |
          docker build -f ./cmd/docs/Dockerfile . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-docs:amd64_latest \
           --no-cache --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=${{ env.git_source }} \
           --build-arg PLATFORM=$PLATFORM_AMD64 --build-arg GO_ARCH=amd64
      - name: Generate build artifacts
        run: |
          mkdir -p /tmp
          docker save -o /tmp/go-bludgeon-docs_amd64-latest.tar.gz ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-docs:amd64_latest
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/go-bludgeon-docs_amd64-latest.tar.gz
          retention-days: 1
      - name: Docker clean-up
        run: |
          docker image prune -f
          docker container prune -f

  github_pages_build:
    needs:
      [
        validate_swagger_changes,
        validate_swagger_employees,
        validate_swagger_timers,
      ]
    runs-on: ubuntu-latest
    env:
      REPO: https://github.com/swagger-api/swagger-ui
      TAG: v4.15.5
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate Static Swagger
        run: |
          git -c advice.detachedHead=false clone --depth 1 --branch "$TAG" "$REPO" ./tmp/swagger-ui
          mkdir ./tmp/swagger
          cp -r ./tmp/swagger-ui/dist ./tmp/swagger/dist
          cp ./cmd/docs/swagger/index.html ./tmp/swagger
          cp ./cmd/docs/swagger/swagger-initializer.js ./tmp/swagger/dist/swagger-initializer.js
          cp /tmp/swagger-timers.json ./tmp/swagger/swagger-timers.json
          cp /tmp/swagger-employees.json ./tmp/swagger/swagger-employees.json
          cp /tmp/swagger-changes.json ./tmp/swagger/swagger-changes.json
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./tmp/swagger
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  github_pages_deploy:
    needs: ["github_pages_build"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
