name: healthcheck_pull_request

on:
  pull_request:
    paths:
      - "healthcheck/**"

env:
  FOLDER_NAME: "healthcheck"
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}-healthcheck
  GO_LINT_VERSION: "v1.59.0"
  GO_VERSION: "1.21"
  GO_CACHE_DEPENDENCY_PATHS: |
    healthcheck/go.sum
  PROTOC_VERSION: "3.20.1"
  PROTOC_GEN_GO_VERSION: "v1.28.0"
  PROTOC_GEN_GO_GRPC_VERSION: "v1.2"
  PROTO_LINT_VERSION: "0.38.3"
  LINTER_VERSION: "v1.59.0"
  PLATFORM_AMD64: linux/amd64
  PLATFORM_ARMV7: linux/arm/v7
  RETENTION_DAYS: 7
  DEFAULT_BRANCH: main

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      version_source: ${{ steps.environment.outputs.version_source }}
      version_target: ${{ steps.environment.outputs.version_target }}
      docker_image_name_ghcr: ${{ steps.environment.outputs.docker_image_name_ghcr }}
      docker_image_name_ecr: ${{ steps.environment.outputs.docker_image_name_ecr }}
      git_source: ${{ steps.environment.outputs.git_source }}
      component_name: ${{ steps.environment.outputs.component_name }}
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/environment@v1
        id: environment
        with:
          folder-name: ${{ env.FOLDER_NAME }}

  go_lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/go_lint@v1
        with:
          folder-name: ${{ env.FOLDER_NAME }}
          golang-version: ${{ env.GO_VERSION}}
          golang-cache-dependency-paths: ${{ env.GO_CACHE_DEPENDENCY_PATHS}}
          linter-version: ${{ env.LINTER_VERSION}}

  proto_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Lint Protos
        uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          protolint_version: ${{ env.PROTO_LINT_VERSION }}
          protolint_flags: -config_path=./healthcheck/.protolint.yaml ./healthcheck/data/pb/*.proto

  proto_validate:
    needs: [proto_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Protoc
        run: |
          PROTOC_ZIP=protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip
          curl -OL --silent https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@${{ env.PROTOC_GEN_GO_VERSION }}
      - name: Install protoc-gen-go-grpc
        run: |
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@${{ env.PROTOC_GEN_GO_GRPC_VERSION }}
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Build protos
        working-directory: /home/runner/work/go-bludgeon/go-bludgeon/healthcheck/data/
        run: |
          protoc -I="./pb" --go_opt=paths=source_relative --go_out="/tmp" --go-grpc_opt=paths=source_relative --go-grpc_out="/tmp" ./pb/*.proto
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/healthcheck.pb.go
            /tmp/healthcheck_grpc.pb.go
            /tmp/timeslices.pb.go
            /tmp/timeslices_grpc.pb.go
      - name: Compare healthcheck.pb.go
        if: always()
        working-directory: /home/runner/work/go-bludgeon/go-bludgeon/healthcheck/data/pb/
        run: |
          if cmp --silent -- "./healthcheck.pb.go" "/tmp/healthcheck.pb.go"; then
            echo "generated proto files are identical"
          else
            echo "one or more proto files generated don't match"
            exit 1
          fi
      - name: Compare healthcheck_grpc.pb.go
        if: always()
        working-directory: /home/runner/work/go-bludgeon/go-bludgeon/healthcheck/data/pb/
        run: |
          if cmp --silent -- "./healthcheck_grpc.pb.go" "/tmp/healthcheck_grpc.pb.go"; then
          echo "generated proto files are identical"
          else
          echo "one or more proto files generated don't match"
          exit 1
          fi

  version_validate:
    needs: [environment]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/version_validate@v1
        with:
          folder-name: ${{ env.FOLDER_NAME }}
          default-branch: ${{ env.DEFAULT_BRANCH }}
          version-source: ${{ needs.environment.outputs.version_source }}
          version-target: ${{ needs.environment.outputs.version_target }}

  go_test_server:
    needs: [go_lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/test@v1
        with:
          folder-name: ${{ env.FOLDER_NAME }}
          golang-version: ${{ env.GO_VERSION}}
          golang-cache-dependency-paths: ${{ env.GO_CACHE_DEPENDENCY_PATHS}}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker_test
          path: |
            /tmp/go-bludgeon-healthcheck.log
            /tmp/go-bludgeon-healthcheck.out
            /tmp/go-bludgeon-healthcheck_services.log

  docker_build_amd64:
    needs: [environment, go_test_server, proto_validate]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      docker_image: ${{ steps.docker_build.outputs.docker_image }}
      docker_image_file: ${{ steps.docker_build.outputs.docker_image_file }}
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/docker_build@v1
        id: docker_build
        with:
          folder-name: ${{ env.FOLDER_NAME }}
          docker-platform: ${{ env.PLATFORM_AMD64 }}
          docker-image-name: ${{ env.DOCKER_IMAGE_NAME }}
          docker-tag-prefix: amd64
          version: ${{ needs.environment.outputs.version_source }}
          git-source: ${{ needs.environment.outputs.git_source }}
          go-arch: amd64
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker_build_amd64
          path: |
            ${{ steps.docker_build.outputs.docker_build_log }}
            ${{ steps.docker_build.outputs.docker_image_file }}
          retention-days: ${{ env.RETENTION_DAYS }}

  docker_build_armv7:
    needs: [environment, go_test, proto_validate]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      docker_image: ${{ steps.docker_build.outputs.docker_image }}
      docker_image_file: ${{ steps.docker_build.outputs.docker_image_file }}
    steps:
      - uses: antonio-alexander/go-bludgeon/.github/actions/docker_build@v1
        id: docker_build
        with:
          folder-name: ${{ env.FOLDER_NAME }}
          docker-platform: ${{ env.PLATFORM_ARMV7 }}
          docker-image-name: ${{ env.DOCKER_IMAGE_NAME }}
          docker-tag-prefix: armv7
          version: ${{ needs.environment.outputs.version_source }}
          git-source: ${{ needs.environment.outputs.git_source }}
          go-arch: arm
          go-arm: 7
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker_build_amd64
          path: |
            ${{ steps.docker_build.outputs.docker_build_log }}
            ${{ steps.docker_build.outputs.docker_image_file }}
          retention-days: ${{ env.RETENTION_DAYS }}

  go_test_client:
    needs: [docker_build_amd64, docker_build_armv7]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp
      - name: Get environment
        run: |
          version=`cat /tmp/version_source`
          echo "version=$version" >> $GITHUB_ENV
      - name: Load Docker Images
        run: |
          docker load -i /tmp/go-bludgeon-healthcheck_amd64-${{ env.version }}.tar.gz
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-healthcheck:amd64_${{ env.version }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-healthcheck:latest
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test healthcheck client
        run: |
          cd /home/runner/work/go-bludgeon/go-bludgeon/healthcheck
          go mod download
          make run
          go test -v ./client/... -coverprofile /tmp/go-bludgeon-healthcheck-client.out | tee /tmp/go-bludgeon-healthcheck-client.log
          docker compose logs >> /tmp/go-bludgeon-healthcheck-client_services.log
      - name: Docker clean-up
        if: always()
        run: |
          make stop
          docker image prune -f
          docker container prune -f
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /tmp/go-bludgeon-healthcheck_client.log
            /tmp/go-bludgeon-healthcheck_client.out
            /tmp/go-bludgeon-healthcheck-client_services.log
